### ISSUE TITLE
Archive data rather than deleting it

### ISSUE THREAD

**Issue by bytorbrynden** [sparkstudios/CJSKA-Sync-Bot#1]
In the old "sync bot", if we found data on Firebase that was no longer returned in our calls to the Khan Academy CS API, the bot would remove that "item" from Firebase, entirely...

I have mixed emotions about this, as, on one hand, it prevents data that no longer exists, from showing up in the contest judging system, **however**, on the other hand, there's a small chance that valid data might be deleted from Firebase, by accident.

Perhaps we should add an `archived` property to data that doesn't get returned by the KA CS API, rather than removing it entirely. If we do that, we can easily get the data back into CJSKA, if something goes wrong.

/cc @MikaalSky, @JavascriptFTW

**Comment by MrMagma** [comment]
I don't see any reason  why we shouldn't just archive stuff except for possible concerns with storage, but as far as I know we're fine in that respect.

**Comment by bytorbrynden** [comment]
@JavascriptFTW, I thought the same thing about storage, but I think we should be fine.

Currently, we're only using 4.75MB out of 1GB.

**Comment by codeHusky** [comment]
Doesn't seem like a problem, we could really just clear items of the archive that are > 1 month old.

**Comment by bytorbrynden** [comment]
Good point @MikaalSky; if there gets to be too many archived items in Firebase that don't exist on Khan Academy anymore, we can always just delete them manually.

**Comment by bytorbrynden** [comment]
Implemented this idea in https://github.com/sparkstudios/CJSKA-Sync-Bot/commit/ac09adaaa82c29e1ea43a861049c940af6037cc1.

Please note, this change also includes a change to our Firebase security rules.
