### ISSUE TITLE
Data is submitted to Firebase as a string, rather than a JSON object

### ISSUE THREAD

**Issue by bytorbrynden** [sparkstudios/CJSKA-Sync-Bot#2]
This isn't ideal, as it makes the Firebase dashboard really hard to get around.

Note to @sparkstudios/developers; from now on, **make sure you run `JSON.parse` on all data you fetch from Firebase**!

**Comment by bytorbrynden** [comment]
I just realized, this causes a major problem-- we cannot access data the way we currently do (IE. `https://contest-judging-sys.firebaseio.com/contests/<contestId>/entryKeys`).

With strings, our security rules are also invalidated...

**Comment by MrMagma** [comment]
Just looked very briefly at the code. Perhaps we need to specify a data type of json on our requests to Firebase?

**Comment by bytorbrynden** [comment]
@JavascriptFTW, I'm not entirely sure why I didn't think of that... If we _can_ specify the `Content-Type` header, then we might actually be able to fix this.

**Comment by bytorbrynden** [comment]
It looks like we'll be able to fix this: http://docs.python-requests.org/en/latest/user/quickstart/#custom-headers
